### ISSUE TITLE
Response `Content-type` is missing encoding

### ISSUE THREAD

**Issue by aoles** [GIScience/openelevationservice#18]
Currently the response header contains just `Content-Type: application/json` and does not specify any encoding unlike the rest of ORS endpoints. This leads to warnings/errors in certain applications as it is not clear which charset should be used for parsing the response, see e.g. https://github.com/GIScience/openrouteservice-r/issues/54.

Please consider appending `charset=utf-8` to `Content-Type`.

Just FYI, there has been a [similar issue with openpoiservice](https://github.com/GIScience/openpoiservice/issues/25) a while ago, now fixed.

**Comment by nilsnolde** [comment]
jup, similar to #17. will fix next week.

**Comment by nilsnolde** [comment]
Actually, I've been reading up about this a little. Encoding is not needed as a response header for the MIME type, since it's implicitly UTF and clients can deduce from the first bytes if its UTF-8/-16/-32, see [SO answer here](https://stackoverflow.com/a/29807846/2582935).

It's not explicitly wrong to return a `charset`, it's just not defined for `application/json`. So, no need to change anything in ORS either.

**Comment by aoles** [comment]
Thank you for following up on this, I will then see into implementing a solution which hides the obscure warning on the client side.

Cheers,
Andrzej

**Comment by nilsnolde** [comment]
If there is a warning in your http lib, that should qualify as a bug, as it's not standard conform, I guess.

**Comment by aoles** [comment]
Actually, it's not a warning but rather a message. However, to the end user this is not much of a difference, I suppose (initially I thought too it's a warning).
```
No encoding supplied: defaulting to UTF-8
```
But I agree that it seems obsolete, I will communicate this to the maintainer.
